// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createPasswordResetToken = `-- name: CreatePasswordResetToken :one
INSERT INTO password_reset_tokens (account_id, token_hash, expires_at)
VALUES ($1, $2, $3)
    RETURNING id, account_id, token_hash, expires_at, used_at, created_at
`

type CreatePasswordResetTokenParams struct {
	AccountID uuid.UUID `json:"account_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error) {
	row := q.db.QueryRowContext(ctx, createPasswordResetToken, arg.AccountID, arg.TokenHash, arg.ExpiresAt)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (account_id, token_hash, expires_at)
VALUES ($1, $2, $3)
    RETURNING id, account_id, token_hash, expires_at, revoked_at, created_at
`

type CreateRefreshTokenParams struct {
	AccountID uuid.UUID `json:"account_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, createRefreshToken, arg.AccountID, arg.TokenHash, arg.ExpiresAt)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, nim, role, status, must_change_password, created_at, updated_at
FROM accounts
WHERE id = $1 LIMIT 1
`

type GetAccountByIDRow struct {
	ID                 uuid.UUID    `json:"id"`
	Nim                string       `json:"nim"`
	Role               string       `json:"role"`
	Status             string       `json:"status"`
	MustChangePassword bool         `json:"must_change_password"`
	CreatedAt          sql.NullTime `json:"created_at"`
	UpdatedAt          sql.NullTime `json:"updated_at"`
}

func (q *Queries) GetAccountByID(ctx context.Context, id uuid.UUID) (GetAccountByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getAccountByID, id)
	var i GetAccountByIDRow
	err := row.Scan(
		&i.ID,
		&i.Nim,
		&i.Role,
		&i.Status,
		&i.MustChangePassword,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByNIM = `-- name: GetAccountByNIM :one
SELECT id, nim, password_hash, role, status, must_change_password, created_at, updated_at
FROM accounts
WHERE nim = $1 LIMIT 1
`

func (q *Queries) GetAccountByNIM(ctx context.Context, nim string) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccountByNIM, nim)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Nim,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.MustChangePassword,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPasswordResetToken = `-- name: GetPasswordResetToken :one
SELECT id, account_id, token_hash, expires_at, used_at
FROM password_reset_tokens
WHERE token_hash = $1 AND used_at IS NULL AND expires_at > CURRENT_TIMESTAMP LIMIT 1
`

type GetPasswordResetTokenRow struct {
	ID        uuid.UUID    `json:"id"`
	AccountID uuid.UUID    `json:"account_id"`
	TokenHash string       `json:"token_hash"`
	ExpiresAt time.Time    `json:"expires_at"`
	UsedAt    sql.NullTime `json:"used_at"`
}

func (q *Queries) GetPasswordResetToken(ctx context.Context, tokenHash string) (GetPasswordResetTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getPasswordResetToken, tokenHash)
	var i GetPasswordResetTokenRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT id, account_id, token_hash, expires_at, revoked_at
FROM refresh_tokens
WHERE token_hash = $1 AND revoked_at IS NULL AND expires_at > CURRENT_TIMESTAMP LIMIT 1
`

type GetRefreshTokenRow struct {
	ID        uuid.UUID    `json:"id"`
	AccountID uuid.UUID    `json:"account_id"`
	TokenHash string       `json:"token_hash"`
	ExpiresAt time.Time    `json:"expires_at"`
	RevokedAt sql.NullTime `json:"revoked_at"`
}

func (q *Queries) GetRefreshToken(ctx context.Context, tokenHash string) (GetRefreshTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getRefreshToken, tokenHash)
	var i GetRefreshTokenRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_logs (actor_id, action, resource, details, ip_address)
VALUES ($1, $2, $3, $4, $5)
`

type InsertAuditLogParams struct {
	ActorID   uuid.NullUUID         `json:"actor_id"`
	Action    string                `json:"action"`
	Resource  string                `json:"resource"`
	Details   pqtype.NullRawMessage `json:"details"`
	IpAddress sql.NullString        `json:"ip_address"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.ExecContext(ctx, insertAuditLog,
		arg.ActorID,
		arg.Action,
		arg.Resource,
		arg.Details,
		arg.IpAddress,
	)
	return err
}

const markPasswordResetTokenAsUsed = `-- name: MarkPasswordResetTokenAsUsed :exec
UPDATE password_reset_tokens
SET used_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) MarkPasswordResetTokenAsUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markPasswordResetTokenAsUsed, id)
	return err
}

const revokeAllAccountRefreshTokens = `-- name: RevokeAllAccountRefreshTokens :exec
UPDATE refresh_tokens
SET revoked_at = CURRENT_TIMESTAMP
WHERE account_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllAccountRefreshTokens(ctx context.Context, accountID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, revokeAllAccountRefreshTokens, accountID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens
SET revoked_at = CURRENT_TIMESTAMP
WHERE token_hash = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, revokeRefreshToken, tokenHash)
	return err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE accounts
SET password_hash = $2,
    must_change_password = false,
    status = 'ACTIVE',
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdatePasswordParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.ExecContext(ctx, updatePassword, arg.ID, arg.PasswordHash)
	return err
}
