// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: iam.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (id, nim, password_hash, role, status, must_change_password)
VALUES ($1, $2, $3, $4, $5, $6)
    RETURNING id, nim, role, status
`

type CreateAccountParams struct {
	ID                 uuid.UUID `json:"id"`
	Nim                string    `json:"nim"`
	PasswordHash       string    `json:"password_hash"`
	Role               string    `json:"role"`
	Status             string    `json:"status"`
	MustChangePassword bool      `json:"must_change_password"`
}

type CreateAccountRow struct {
	ID     uuid.UUID `json:"id"`
	Nim    string    `json:"nim"`
	Role   string    `json:"role"`
	Status string    `json:"status"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (CreateAccountRow, error) {
	row := q.db.QueryRowContext(ctx, createAccount,
		arg.ID,
		arg.Nim,
		arg.PasswordHash,
		arg.Role,
		arg.Status,
		arg.MustChangePassword,
	)
	var i CreateAccountRow
	err := row.Scan(
		&i.ID,
		&i.Nim,
		&i.Role,
		&i.Status,
	)
	return i, err
}

const createProfile = `-- name: CreateProfile :exec
INSERT INTO profiles (account_id, full_name, nickname, email, is_public)
VALUES ($1, $2, $3, $4, $5)
`

type CreateProfileParams struct {
	AccountID uuid.UUID      `json:"account_id"`
	FullName  string         `json:"full_name"`
	Nickname  sql.NullString `json:"nickname"`
	Email     sql.NullString `json:"email"`
	IsPublic  bool           `json:"is_public"`
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) error {
	_, err := q.db.ExecContext(ctx, createProfile,
		arg.AccountID,
		arg.FullName,
		arg.Nickname,
		arg.Email,
		arg.IsPublic,
	)
	return err
}

const createTOTPSecret = `-- name: CreateTOTPSecret :exec
INSERT INTO admin_totp_secrets (account_id, totp_secret, backup_codes)
VALUES ($1, $2, $3)
`

type CreateTOTPSecretParams struct {
	AccountID   uuid.UUID       `json:"account_id"`
	TotpSecret  string          `json:"totp_secret"`
	BackupCodes json.RawMessage `json:"backup_codes"`
}

func (q *Queries) CreateTOTPSecret(ctx context.Context, arg CreateTOTPSecretParams) error {
	_, err := q.db.ExecContext(ctx, createTOTPSecret, arg.AccountID, arg.TotpSecret, arg.BackupCodes)
	return err
}

const getProfileByAccountID = `-- name: GetProfileByAccountID :one
SELECT p.account_id, p.full_name, p.nickname, p.email, p.bio, p.is_public, a.nim, a.role, a.status
FROM profiles p
         JOIN accounts a ON p.account_id = a.id
WHERE p.account_id = $1 LIMIT 1
`

type GetProfileByAccountIDRow struct {
	AccountID uuid.UUID      `json:"account_id"`
	FullName  string         `json:"full_name"`
	Nickname  sql.NullString `json:"nickname"`
	Email     sql.NullString `json:"email"`
	Bio       sql.NullString `json:"bio"`
	IsPublic  bool           `json:"is_public"`
	Nim       string         `json:"nim"`
	Role      string         `json:"role"`
	Status    string         `json:"status"`
}

func (q *Queries) GetProfileByAccountID(ctx context.Context, accountID uuid.UUID) (GetProfileByAccountIDRow, error) {
	row := q.db.QueryRowContext(ctx, getProfileByAccountID, accountID)
	var i GetProfileByAccountIDRow
	err := row.Scan(
		&i.AccountID,
		&i.FullName,
		&i.Nickname,
		&i.Email,
		&i.Bio,
		&i.IsPublic,
		&i.Nim,
		&i.Role,
		&i.Status,
	)
	return i, err
}

const getTOTPSecret = `-- name: GetTOTPSecret :one
SELECT totp_secret, is_verified, backup_codes
FROM admin_totp_secrets
WHERE account_id = $1 LIMIT 1
`

type GetTOTPSecretRow struct {
	TotpSecret  string          `json:"totp_secret"`
	IsVerified  bool            `json:"is_verified"`
	BackupCodes json.RawMessage `json:"backup_codes"`
}

func (q *Queries) GetTOTPSecret(ctx context.Context, accountID uuid.UUID) (GetTOTPSecretRow, error) {
	row := q.db.QueryRowContext(ctx, getTOTPSecret, accountID)
	var i GetTOTPSecretRow
	err := row.Scan(&i.TotpSecret, &i.IsVerified, &i.BackupCodes)
	return i, err
}

const suspendAccount = `-- name: SuspendAccount :exec
UPDATE accounts
SET status = 'SUSPENDED', updated_at = NOW()
WHERE id = $1
`

func (q *Queries) SuspendAccount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, suspendAccount, id)
	return err
}

const updateProfile = `-- name: UpdateProfile :exec
UPDATE profiles
SET full_name = COALESCE($2, full_name),
    nickname = COALESCE($3, nickname),
    bio = COALESCE($4, bio),
    is_public = COALESCE($5, is_public),
    updated_at = NOW()
WHERE account_id = $1
`

type UpdateProfileParams struct {
	AccountID uuid.UUID      `json:"account_id"`
	FullName  sql.NullString `json:"full_name"`
	Nickname  sql.NullString `json:"nickname"`
	Bio       sql.NullString `json:"bio"`
	IsPublic  sql.NullBool   `json:"is_public"`
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) error {
	_, err := q.db.ExecContext(ctx, updateProfile,
		arg.AccountID,
		arg.FullName,
		arg.Nickname,
		arg.Bio,
		arg.IsPublic,
	)
	return err
}

const verifyTOTP = `-- name: VerifyTOTP :exec
UPDATE admin_totp_secrets
SET is_verified = TRUE
WHERE account_id = $1
`

func (q *Queries) VerifyTOTP(ctx context.Context, accountID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, verifyTOTP, accountID)
	return err
}
