// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Account struct {
	ID                 uuid.UUID    `json:"id"`
	Nim                string       `json:"nim"`
	PasswordHash       string       `json:"password_hash"`
	Role               string       `json:"role"`
	Status             string       `json:"status"`
	MustChangePassword bool         `json:"must_change_password"`
	CreatedAt          sql.NullTime `json:"created_at"`
	UpdatedAt          sql.NullTime `json:"updated_at"`
}

type AdminTotpSecret struct {
	AccountID   uuid.UUID       `json:"account_id"`
	TotpSecret  string          `json:"totp_secret"`
	IsVerified  bool            `json:"is_verified"`
	BackupCodes json.RawMessage `json:"backup_codes"`
	CreatedAt   sql.NullTime    `json:"created_at"`
}

type AuditLog struct {
	ID        uuid.UUID             `json:"id"`
	ActorID   uuid.NullUUID         `json:"actor_id"`
	Action    string                `json:"action"`
	Resource  string                `json:"resource"`
	Details   pqtype.NullRawMessage `json:"details"`
	IpAddress sql.NullString        `json:"ip_address"`
	CreatedAt sql.NullTime          `json:"created_at"`
}

type PasswordResetToken struct {
	ID        uuid.UUID    `json:"id"`
	AccountID uuid.UUID    `json:"account_id"`
	TokenHash string       `json:"token_hash"`
	ExpiresAt time.Time    `json:"expires_at"`
	UsedAt    sql.NullTime `json:"used_at"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Profile struct {
	AccountID uuid.UUID      `json:"account_id"`
	FullName  string         `json:"full_name"`
	Nickname  sql.NullString `json:"nickname"`
	Email     sql.NullString `json:"email"`
	Bio       sql.NullString `json:"bio"`
	IsPublic  bool           `json:"is_public"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}

type RefreshToken struct {
	ID        uuid.UUID    `json:"id"`
	AccountID uuid.UUID    `json:"account_id"`
	TokenHash string       `json:"token_hash"`
	ExpiresAt time.Time    `json:"expires_at"`
	RevokedAt sql.NullTime `json:"revoked_at"`
	CreatedAt sql.NullTime `json:"created_at"`
}
