// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	GetAccountByID(ctx context.Context, id uuid.UUID) (GetAccountByIDRow, error)
	GetAccountByNIM(ctx context.Context, nim string) (Account, error)
	GetPasswordResetToken(ctx context.Context, tokenHash string) (GetPasswordResetTokenRow, error)
	GetRefreshToken(ctx context.Context, tokenHash string) (GetRefreshTokenRow, error)
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error
	MarkPasswordResetTokenAsUsed(ctx context.Context, id uuid.UUID) error
	RevokeAllAccountRefreshTokens(ctx context.Context, accountID uuid.UUID) error
	RevokeRefreshToken(ctx context.Context, tokenHash string) error
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error
}

var _ Querier = (*Queries)(nil)
